const products = [
    {
        id: 1,
        name: 'Trailblazer Sneakers',
        description: 'Lightweight and durable trail-running shoes.',
        price: 34.99,
        imageUrl: '/p1.png',
        innerdescription: 'The Trailblazer Sneakers are designed for runners who want to take their training off-road. These lightweight and durable shoes are perfect for trail running, hiking, and other outdoor activities. The Trailblazer Sneakers feature a rugged outsole with deep lugs for excellent traction on a variety of surfaces. The upper is made from breathable mesh and synthetic materials that provide support and protection without adding extra weight. With a cushioned midsole and a comfortable fit, the Trailblazer Sneakers are ready to take on any adventure.',
    },
    {
        id: 2,
        name: 'Urban Glide',
        description: 'Comfortable sneakers for daily wear.',
        innerdescription: 'The Urban Glide sneakers are designed for everyday comfort and style. These versatile shoes are perfect for running errands, going for walks, or just hanging out with friends. The Urban Glide sneakers feature a lightweight and breathable upper that keeps your feet cool and comfortable all day long. The cushioned midsole provides support and shock absorption, while the durable outsole offers traction and stability on a variety of surfaces. With a sleek design and a comfortable fit, the Urban Glide sneakers are the perfect choice for any casual occasion.',
        price: 23.49,
        imageUrl: '/p2.png',
    },
    {
        id: 3,
        name: 'Pro Runner 3000',
        description: 'High-performance shoes for serious runners.',
        innerdescription: 'The Pro Runner 3000 is a high-performance running shoe designed for serious runners who want to take their training to the next level. These shoes feature a lightweight and breathable upper that provides support and stability without adding extra weight. The cushioned midsole offers excellent shock absorption and energy return, while the durable outsole provides traction and durability on a variety of surfaces. With a sleek design and a comfortable fit, the Pro Runner 3000 is the perfect choice for runners who want to go the distance.',
        price: 45.99,
        imageUrl: '/p3.png',
    },
    {
        id: 4,
        name: 'Classic Comfort',
        description: 'Timeless design with modern cushioning.',
        innerdescription: 'The Classic Comfort shoes combine timeless design with modern cushioning for a comfortable and stylish look. These shoes feature a durable upper with a classic lace-up design that provides a secure fit. The cushioned midsole offers support and shock absorption, while the durable outsole provides traction and stability on a variety of surfaces. With a sleek design and a comfortable fit, the Classic Comfort shoes are the perfect choice for any casual occasion.',
        price: 28.79,
        imageUrl: '/p4.png',
    },
    {
        id:5,
        name: 'Product 1',
        description: 'Famous Filmstar Shoes',
        price: 29.99,
        imageUrl: '/p1.png',
    },
    {
        id:6,
        name: 'Shoes No 2',
        description: 'A.M ',
        price: 39.99,
        imageUrl: '/p2.png',
    },
    {
        id:7,
        name: 'Item No 3',
        description: 'Best Shoes',
        price: 49.99,
        imageUrl: '/p3.png',
    },
    {
        id:8,
        name: 'Product 2',
        description: 'All Features U Need',
        price: 49.99,
        imageUrl: '/p4.png',
    },
    {
        id:9,
        name: 'Item No 3',
        description: 'Best Shoes',
        price: 49.99,
        imageUrl: '/p3.png',
    },
    {
        id:10,
        name: 'Product 2',
        description: 'All Features U Need',
        price: 49.99,
        imageUrl: '/p4.png',
    },
    {
        id:11,
        name: 'Product 1',
        description: 'Famous Filmstar Shoes',
        price: 29.99,
        imageUrl: '/p1.png',
    },
    {
        id:12,
        name: 'Shoes No 2',
        description: 'A.M ',
        price: 39.99,
        imageUrl: '/p2.png',
    },
    {
        id:13,
        name: 'Item No 3',
        description: 'Best Shoes',
        price: 49.99,
        imageUrl: '/p3.png',
    },
    {
        id:14,
        name: 'Product 2',
        description: 'All Features U Need',
        price: 49.99,
        imageUrl: '/p4.png',
    },
    {
        id:15,
        name: 'Product 2',
        description: 'All Features U Need',
        price: 49.99,
        imageUrl: '/p4.png',
    }
];

export default products;
